In [82]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler, LabelEncoder
import sklearn.model_selection
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn import tree
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB, MultinomialNB
from sklearn import metrics

from nltk.stem import PorterStemmer
from nltk.stem import LancasterStemmer
from nltk.tokenize import sent_tokenize, word_tokenize

from keras.models import Sequential
from keras.layers import Dense, Conv1D, Flatten, MaxPooling1D


import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

import sklearn.model_selection
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn import tree
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB, MultinomialNB
from sklearn import metrics
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.ensemble import RandomForestClassifier


import nltk
from nltk.stem import PorterStemmer
from nltk.stem import LancasterStemmer
from nltk.tokenize import sent_tokenize, word_tokenize
from nltk.corpus import stopwords
from nltk.stem.wordnet import WordNetLemmatizer
nltk.download('wordnet')

#word2vec
from gensim.models import Word2Vec  
import gensim
import string

[nltk_data] Downloading package wordnet to /home/typedoor/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [2]:
PATH = '/home/typedoor/PLBRS/Data/'

In [3]:
sp = pd.read_csv(PATH + 'south_park.csv')

In [7]:
sp_clean = sp[(sp.Character == 'Cartman') | (sp.Character == 'Kyle') | (sp.Character == 'Stan') | (sp.Character == 'Butters') | (sp.Character == 'Randy')].reset_index(drop = True)
sp_clean.shape  

(29622, 4)

In [8]:
sp_copy = sp_clean.copy()[['Character', 'Line']]
sp_copy.Line = sp_copy.Line.apply(sent_tokenize)
sp_copy.Line[0]

['You guys, you guys!', 'Chef is going away.']

In [9]:
def break_up_to_sentences(df):
    result_df = pd.DataFrame(columns = ['Character', 'Line'])
    
    for index, row in df.iterrows():
        if index %1000 == 0:
                print(index)
        
        for sentence in row.Line:

            addition = {'Character': row.Character,'Line': sentence }
            result_df = result_df.append(addition, ignore_index = True)
    
    return result_df
full_df = break_up_to_sentences(sp_copy) 
full_df

0
1000
2000
3000
4000
5000
6000
7000
8000
9000
10000
11000
12000
13000
14000
15000
16000
17000
18000
19000
20000
21000
22000
23000
24000
25000
26000
27000
28000
29000


Character                                               Line
0          Stan                                You guys, you guys!
1          Stan                                Chef is going away.
2          Kyle                                        Going away?
3          Kyle                                      For how long?
4          Stan                                           Forever.
5          Stan  Chef said he's been bored, so he joining a gro...
6       Cartman                                I'm gonna miss him.
7       Cartman  I'm gonna miss Chef and I...and I don't know h...
8          Stan                      Dude, how are we gonna go on?
9          Stan                      Chef was our fuh...f-ffriend.
10        Randy                                    Good-bye, Chef!
11        Randy   Have a great time with the Super Adventure Club!
12         Kyle                             Draw two card, fatass.
13      Cartman                               Reverse to you, Jew.
14         Stan                                       I'll get it.
15         Stan                                         He's back!
16         Kyle                                              Yeah!
17      Cartman                                         All right!
18         Kyle                                              Chef!
19         Kyle                       I can't believe you're back!
20         Stan                         But are you back for good?
21        Randy                                       Oh, finally!
22        Randy  Ohhh, so have you decided you can still belong...
23        Randy  Well, it seems like the Super Adventure Club w...
24        Randy  You must be feeling very happy that you found ...
25        Randy                                             Right?
26        Randy                           Well, come on everybody.
27        Randy  I'm sure Chef would like a little time to get ...
28         Kyle  Well, I- guess we'll see you in school tomorro...
29         Stan                                             Right.
...         ...                                                ...
54781     Randy                                                  ?
54782      Stan                            Dad, you like to drink.
54783      Stan                   So have a drink once in a while.
54784      Stan                                          Have two.
54785      Stan  If you devote your whole life to completely av...
54786     Randy                                      But, maybe...
54787     Randy  I'm just the kind of person who needs to have ...
54788      Stan                                               Naw.
54789      Stan                            All or nothing is easy.
54790      Stan  But learning to drink a little bit, responsibl...
54791      Stan                    Disciprine... come from within.
54792     Randy        How did I manage to raise such a smart kid?
54793      Stan                          I've had a great teacher.
54794     Randy                                        Thanks son.
54795      Stan                     No not you, my karate teacher.
54796      Stan                                 He's really smart.
54797     Randy                                                Oh.
54798     Randy  Well, tell you what: let's leave the car here,...
54799     Randy                  Like to have another beer or two.
54800      Stan                                         All right!
54801     Randy                                           Come on!
54802     Randy                    Or maybe I'll have three beers.
54803      Stan         That's probably okay if you spread it out.
54804     Randy                               Well how about four?
54805      Stan                         I think you're pushing it.
54806     Randy                                  How about twenty?
54807      Stan                             That's not disciprine.
54808     Randy                                      

In [10]:
full_df.groupby('Character').count().Line[sp.groupby('Character').count().Line > 2000]

Character
Butters     5041
Cartman    21122
Kyle       11517
Randy       5284
Stan       11847
Name: Line, dtype: int64

In [26]:
working_df = full_df[(full_df.Character == 'Cartman') | (full_df.Character == 'Kyle') | (full_df.Character == 'Stan')].reset_index(drop = True)
indices = working_df[(working_df.Line == '!') | (working_df.Line == '?')].index
final_df = working_df.drop(index = indices).reset_index(drop = True)


In [23]:
final_df

index Character                                               Line
0          0      Stan                                You guys, you guys!
1          1      Stan                                Chef is going away.
2          2      Kyle                                        Going away?
3          3      Kyle                                      For how long?
4          4      Stan                                           Forever.
5          5      Stan  Chef said he's been bored, so he joining a gro...
6          6   Cartman                                I'm gonna miss him.
7          7   Cartman  I'm gonna miss Chef and I...and I don't know h...
8          8      Stan                      Dude, how are we gonna go on?
9          9      Stan                      Chef was our fuh...f-ffriend.
10        10      Kyle                             Draw two card, fatass.
11        11   Cartman                               Reverse to you, Jew.
12        12      Stan                                       I'll get it.
13        13      Stan                                         He's back!
14        14      Kyle                                              Yeah!
15        15   Cartman                                         All right!
16        16      Kyle                                              Chef!
17        17      Kyle                       I can't believe you're back!
18        18      Stan                         But are you back for good?
19        19      Kyle  Well, I- guess we'll see you in school tomorro...
20        20      Stan                                             Right.
21        21      Stan                                        Uh, see ya.
22        22   Cartman                                          Uh, guys?
23        23   Cartman         Did Chef seem a little, uh, trippy to you?
24        24      Stan                                        Well, look.
25        25      Stan                          he said he's happier now.
26        26      Stan           Maybe he just needs to rest up a little.
27        27      Kyle                                              Yeah.
28        28      Kyle  I'm sure whatever that Super Adventure Club do...
29        29      Stan  Yeah, but whatever, I'm just glad he's back fo...
...      ...       ...                                                ...
43218  44456      Stan                             Dad, we're going back!
43219  44457      Stan                                     Praise Christ.
43220  44458      Stan  Naw, Dad, all the guys are going to Kyle's hos...
43221  44459      Stan      Kenny and Kyle's Dads were hoping you'd come.
43222  44460      Stan                          No, my dad doesn't drink.
43223  44461      Stan                                    Dad, Dad, Stop!
43224  44462      Stan                    Dad, you don't have to do this!
43225  44463      Stan                                You have the power.
43226  44464      Stan         You haven't drank since seeing the statue.
43227  44465      Stan                                              Yeah.
43228  44466      Stan                  The statue wasn't a miracle, Dad.
43229  44467      Stan                          So that means you did it.
43230  44468      Stan  That means you didn't have a drink for five da...
43231  44469      Stan                                                No!
43232  44470      Stan                            Dad, you like to drink.
43233  44471      Stan                   So have a drink once in a while.
43234  44472      Stan                                          Have two.
43235  44473      Stan  If you devote your whole life to completely av...
43236  44474      Stan                                               Naw.
43237  44475      Stan                            All or nothing is easy.
43238  44476      Stan  But learning to drink a little bit, responsibl...
43239  44477      Stan                    Disciprine... come from within.
43240  4447

In [27]:
final_df.to_csv(PATH + 'south_park_sentence_by_sentence.csv', index = False)

In [28]:
simpsons = pd.read_csv(PATH+ 'simpsons.csv')
simpsons.head()

raw_character_text                                       spoken_words
0              Miss Hoover  No, actually, it was a little of both. Sometim...
1             Lisa Simpson                             Where's Mr. Bergstrom?
2              Miss Hoover  I don't know. Although I'd sure like to talk t...
3             Lisa Simpson                         That life is worth living.
4  Edna Krabappel-Flanders  The polls will be open from now until the end ...

In [33]:
simpsons.groupby('raw_character_text').count().spoken_words[simpsons.groupby('raw_character_text').count().spoken_words > 2000]

raw_character_text
Bart Simpson           12995
C. Montgomery Burns     3077
Homer Simpson          27850
Lisa Simpson           10756
Marge Simpson          13172
Moe Szyslak             2808
Ned Flanders            2056
Seymour Skinner         2385
Name: spoken_words, dtype: int64

In [55]:
simpsons.rename(columns = {'raw_character_text': 'Character','spoken_words' : 'Line'}, inplace = True)
simpsons_family = simpsons[(simpsons.Character == 'Bart Simpson') | (simpsons.Character == 'Marge Simpson') | (simpsons.Character == 'Homer Simpson') | (simpsons.Character == 'Lisa Simpson')].reset_index(drop = True)
simpsons_family.dropna(inplace = True)
simpsons_family.head(25)

Character                                               Line
0    Lisa Simpson                             Where's Mr. Bergstrom?
1    Lisa Simpson                         That life is worth living.
2    Bart Simpson                     Victory party under the slide!
3    Lisa Simpson                      Mr. Bergstrom! Mr. Bergstrom!
4    Lisa Simpson                Do you know where I could find him?
5    Lisa Simpson  The train, how like him... traditional, yet en...
6    Lisa Simpson                         I see he touched you, too.
7    Bart Simpson                    Hey, thanks for your vote, man.
8    Bart Simpson  Well, you got that right. Thanks for your vote...
9    Bart Simpson  Well, don't sweat it. Just so long as a couple...
10   Bart Simpson                                             Lewis?
11   Bart Simpson                          Somebody must have voted.
12   Bart Simpson                                             Uh oh.
14   Bart Simpson                                I demand a recount.
15   Bart Simpson                                                No.
16   Lisa Simpson                 Mr. Bergstrom! Hey, Mr. Bergstrom!
17   Lisa Simpson                                 Hey, Lisa, indeed.
18   Lisa Simpson  Oh, I mean, were you just going to leave, just...
19   Lisa Simpson  You can't go! You're the best teacher I'll eve...
20   Lisa Simpson                                        Oh, please.
21   Lisa Simpson                                But I need you too.
22   Lisa Simpson  I, I understand. Mr. Bergstrom, I'm going to m...
23   Lisa Simpson                          Thank you, Mr. Bergstrom.
24   Lisa Simpson  So, I guess this is it? It you don't mind I'll...
25  Homer Simpson  Never thrown a party? What about that big bash...

In [57]:
set(simpsons_family.Character)

{'Bart Simpson', 'Homer Simpson', 'Lisa Simpson', 'Marge Simpson'}

In [60]:
simpsons_family.Line = simpsons_family.Line.apply(sent_tokenize)
simpsons_full = break_up_to_sentences(simpsons_family)
simpsons_full.head(25)

0
1000
2000
3000
4000
5000
6000
7000
8000
10000
11000
12000
13000
14000
15000
16000
17000
18000
19000
20000
21000
22000
23000
24000
25000
26000
27000
28000
29000
30000
31000
32000
33000
34000
35000
36000
37000
38000
39000
40000
41000
42000
43000
44000
45000
46000
47000
48000
49000
50000
51000
52000
53000
54000
55000
59000
60000
61000
62000
63000
65000
66000
67000
68000
69000


Character                                               Line
0   Lisa Simpson                             Where's Mr. Bergstrom?
1   Lisa Simpson                         That life is worth living.
2   Bart Simpson                     Victory party under the slide!
3   Lisa Simpson                                     Mr. Bergstrom!
4   Lisa Simpson                                     Mr. Bergstrom!
5   Lisa Simpson                Do you know where I could find him?
6   Lisa Simpson  The train, how like him... traditional, yet en...
7   Lisa Simpson                         I see he touched you, too.
8   Bart Simpson                    Hey, thanks for your vote, man.
9   Bart Simpson                          Well, you got that right.
10  Bart Simpson                       Thanks for your vote, girls.
11  Bart Simpson                              Well, don't sweat it.
12  Bart Simpson  Just so long as a couple of people did... righ...
13  Bart Simpson                                             Lewis?
14  Bart Simpson                          Somebody must have voted.
15  Bart Simpson                                             Uh oh.
16  Bart Simpson                                I demand a recount.
17  Bart Simpson                                                No.
18  Lisa Simpson                                     Mr. Bergstrom!
19  Lisa Simpson                                Hey, Mr. Bergstrom!
20  Lisa Simpson                                 Hey, Lisa, indeed.
21  Lisa Simpson  Oh, I mean, were you just going to leave, just...
22  Lisa Simpson                                      You can't go!
23  Lisa Simpson            You're the best teacher I'll ever have.
24  Lisa Simpson                                        Oh, please.

In [63]:
simpsons_full.shape

(101914, 2)

In [66]:
indices = simpsons_full[(simpsons_full.Line == '!') | (simpsons_full.Line == '?')].index
simpsons_full = simpsons_full.drop(index = indices).reset_index(drop = True)
simpsons_full.shape

(101167, 2)

In [68]:
simpsons_full.to_csv(PATH+'simpson_family_sentence_by_sentence.csv', index = False)

In [70]:
simpsons_full.groupby('Character').count()

Line
Character           
Bart Simpson   19486
Homer Simpson  46333
Lisa Simpson   15873
Marge Simpson  19475

**Trying to clssify simpsons**


In [75]:
y = simpsons_full.Character.values
from sklearn.feature_extraction.text import TfidfVectorizer
tf=TfidfVectorizer()
text_tf= tf.fit_transform(simpsons_full['Line'])

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    text_tf, y, test_size=0.3, random_state=123)

In [80]:
clf = MultinomialNB().fit(X_train, y_train)
predicted= clf.predict(X_test)
confusion = metrics.confusion_matrix(y_test, predicted, labels = ['Bart Simpson', 'Lisa Simpson','Homer Simpson','Marge Simpson'])
cm = metrics.classification_report(y_test, predicted,labels = ['Bart Simpson', 'Lisa Simpson','Homer Simpson','Marge Simpson'])
print("MultinomialNB Accuracy:",metrics.accuracy_score(y_test, predicted))
print(confusion)
print(cm)

MultinomialNB Accuracy: 0.4947448189515996
[[  565   134  5161    65]
 [  185   318  4135    70]
 [  140    72 13567   146]
 [   57    37  5133   566]]
               precision    recall  f1-score   support

 Bart Simpson       0.60      0.10      0.16      5925
 Lisa Simpson       0.57      0.07      0.12      4708
Homer Simpson       0.48      0.97      0.65     13925
Marge Simpson       0.67      0.10      0.17      5793

    micro avg       0.49      0.49      0.49     30351
    macro avg       0.58      0.31      0.28     30351
 weighted avg       0.55      0.49      0.38     30351



In [83]:
clf = RandomForestClassifier(n_jobs = -1, n_estimators = 7500, bootstrap = True, max_depth = 2,class_weight= 'balanced_subsample').fit(X_train,y_train)
predicted= clf.predict(X_test)
confusion = metrics.confusion_matrix(y_test, predicted, labels = ['Bart Simpson', 'Lisa Simpson','Homer Simpson','Marge Simpson'])
cm = metrics.classification_report(y_test, predicted,labels = ['Bart Simpson', 'Lisa Simpson','Homer Simpson','Marge Simpson'])
print("RF Accuracy:",metrics.accuracy_score(y_test, predicted))
print(confusion)
print(cm)

Random Forest Accuracy: 0.3982735329972653
RF Accuracy: 0.3982735329972653
[[2341 1019 1332 1233]
 [1089 1577  909 1133]
 [3567 1639 5288 3431]
 [ 887  780 1244 2882]]
               precision    recall  f1-score   support

 Bart Simpson       0.30      0.40      0.34      5925
 Lisa Simpson       0.31      0.33      0.32      4708
Homer Simpson       0.60      0.38      0.47     13925
Marge Simpson       0.33      0.50      0.40      5793

    micro avg       0.40      0.40      0.40     30351
    macro avg       0.39      0.40      0.38     30351
 weighted avg       0.45      0.40      0.41     30351

